{% set name = "craftr" %}
{% set version = "2.0.0" %}
{% set sha256 = "01ff3e2291c72f918186e3551bede6dcfdc8ce5ed91c25bbbf218835b3a1b8d0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/craftr-build/craftr/archive/v2.0.0.dev5.tar.gz
  sha256: {{ sha256 }}

build:
  script: python setup.py install --single-version-externally-managed --record record.txt
  number: 0
  skip: true  # [py2k or py36]

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - setuptools
    - colorama ==0.3.7
    - glob2 ==0.5
    - jsonschema ==2.5.1
    - ninja
    - ninja_syntax ==1.6.0
    - nr ==1.3.5
    - termcolor ==1.1.0
    - werkzeug ==0.11.11

test:
  commands:
    - craftr -h

about:
  home: https://craftr.net
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: Meta build system based on Ninja and Python
  description: |
    Craftr is a next generation build system based on Ninja and Python that
    features modular and cross-platform build definitions at the flexibility of a
    Python script and provides access to multiple levels of build automation
    abstraction.
  doc_url: http://craftr.readthedocs.io
  dev_url: https://github.com/craftr-build/craftr

extra:
  recipe-maintainers:
    - dfroger
