travis:
  secure:
    BINSTAR_TOKEN: pzFvrQV5N7rGlyl/XBaCMCubIyUNSW5m/yQ0/LkUIk6jkRECTfqYpfKSbiJi4HiVmUya+FIOsw/PrLIPpIIxhQ3ok1YXyV0ths3lA5S4KTDNHzZslbbN26/e2HxRcdM5mF7suy1uO4IKF4fL4UbPho7SgVY+LgRxSLM/uIdrbdah5pyxDnhq1M2g+5q7ngxMIrUy4ekeUna0+5dWeQAqIUscWZKQ8SXpixeOg0P4xsZn9Npfw6XxfrBA6zQyhAkN3ErSyQA8OiDRsWBbNLSw7djL+V73QGn6MkkDzrS9A01GtCaZYMsNvTxHDO8bzQW39/Ag07JfGa2xtkoq5PUxtv+FI3FI0QSiNsRUT1wBjDs9GbZOFow63prOqocxEGMv08CQBqa7t2zLDqGJEWO04yaMZLmRd9I/FEoc+zewnVqgjUxkZ61wuJb1/bexF/m0LM8j51WSMV5feVej3atPuvA35Zz+MSW9DsbkiehqvVYBjUpePB6gh9IMs66FW59fdemHOtjGfjMhbGF5ma9bsaJawd+X71bsLPMSWJ1f+O818qZx/xkBC78dTPjcoPDvpHvxJSW80h9yxamVcX7vRjbmE1lyWnisMBBtrlztxFqOR1C5Z9jTabJXfrjrJXwhKbrIOnl1LARgdCFA7mNyQGAhPKnK3PMXIamh+LEw4oY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
