travis:
  secure:
    BINSTAR_TOKEN: JVATrmaSsFwHdh//RICPDHYOSKJIbe9bQbY0+B+kdL0aRBM1BtzMCHrhsO3d/o7VYyDOp1DpDXsCiebbokHTNN2LkTquFCc5mvMkmwwGvjJC/HPAqmaW89loUVnOgYdik3PFe9sH6C94Ud4Aa2fkJiPfqzHViSnxNRCtfKGGP/F5/gOtHc4Hv8A9A96V8x7LuwVjJ1talYl0o9RQcpU/pcc8lH84SNGinB/FV9AIsvrylPNtny3g6zofatk+roEd+OXKzg5mAZ+7rgjHxN0u5HhD1EgRIy+I+kLFIWMba8mp+b/iOeYl2iIBt0n3ii8FR/ZMkW7QYe1yZC64fKMuMd7V6uA/QrKyv2oq2TJ7opilikXAD2EoWJ/aaOFUaPvtrkkV1198DXcqKVHbSq8OglS9ITFD7c5bQ+9YZX39LmAWKi6sPkKOi5yVbCnqJQzIVjj42iWRHNXuNvryATtJXIIsDm9J4sww5h6ruH2Yrl2UJuXG0PWi6P0sQCXs2TZrfsUr6A3xHAXAmU6rtxY4cclgJm7opJAoPEWi0ofbEO/DV0Y+6wm3O0j00k6brogVY3Pp/LXMlkBh9eguNZnssVsPixlkVl+QWbAUyu+zE0Vy8KOpkSvO4u8hIoAGG0GaeNzUWglC5LGJaCV5OC5mOTSXFq4AJPATSAV4heJ5fwU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
